# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Takenotesctl < Formula
  desc "takenotesctl is cli app to and view notes from cli. Notes can be filtered by created date, can be searched by matching fields text and can also be exported in a csv file"
  homepage "https://github.com/NiteeshKMishra/takenotesctl"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/NiteeshKMishra/takenotesctl/releases/download/v1.0.0/takenotesctl_Darwin_arm64.tar.gz"
      sha256 "9e3f954a4ecde59310e61cd239a108e19f0f1c387f1c0279d005355caf71d756"

      def install
        bin.install "takenotesctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/NiteeshKMishra/takenotesctl/releases/download/v1.0.0/takenotesctl_Darwin_x86_64.tar.gz"
      sha256 "045e9bebb2b62ecf3a1089198e4d843820aac1c478d55bc7d0b9c71fcc767a51"

      def install
        bin.install "takenotesctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/NiteeshKMishra/takenotesctl/releases/download/v1.0.0/takenotesctl_Linux_x86_64.tar.gz"
      sha256 "95840de4551d8827af8462e1369f3491bec3a553527232aef96da0fc39ff4ef3"

      def install
        bin.install "takenotesctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NiteeshKMishra/takenotesctl/releases/download/v1.0.0/takenotesctl_Linux_arm64.tar.gz"
      sha256 "2bb4a136b0470f990eb8961812017ca4b2ec4975da6e2fa030129cc586022184"

      def install
        bin.install "takenotesctl"
      end
    end
  end
end
